"""GitHub backup scaffolding (CW-4 — opt-in)."""

from __future__ import annotations

import os
from typing import Any

from agent_core_hatchery.config import HatchConfig

_HOOK_TEMPLATE = """#!/usr/bin/env bash
# Generated by agent-core-hatchery for {being_name}.
# Backup the vault's Memory/ to GitHub. Invoked by the
# {being_name_lower}-github_backup scheduler job.
set -euo pipefail

VAULT_ROOT="{vault_root}"
REPO_URL="{repo_url}"

# Never prompt. This runs headless from the scheduler, where a credential
# prompt is not a question anyone can answer -- it is a hang. Failing fast is
# the only useful behaviour, and the SHA check below turns it into a report.
export GIT_TERMINAL_PROMPT=0

cd "$VAULT_ROOT"
if [ ! -d Memory/.git ]; then
  cd Memory
  git init
  git remote add origin "$REPO_URL"
  cd ..
fi
cd Memory

# `symbolic-ref`, not `rev-parse --abbrev-ref HEAD`. On the FIRST run the repo
# was just `git init`ed and has no commits, and rev-parse errors on an unborn
# branch -- which under `set -e` aborts the very run that is supposed to
# establish the backup.
BRANCH=$(git symbolic-ref --short HEAD)
git add -A

# Distinguish "nothing to commit" from "commit failed". The previous
# `|| true` treated them alike, so a genuinely broken commit read as a quiet
# no-op.
if git diff --cached --quiet; then
  echo "Nothing to commit; pushing anyway (a push is a no-op when current)."
else
  git commit -m "backup $(date -Iseconds)"
fi

# `|| PUSH_RC=$?` rather than `git push` followed by `PUSH_RC=$?`. Under
# `set -e` a bare failing push aborts the script AT THAT LINE, skipping the
# verification below -- so the one path that most needs checking is the only
# path that never reaches it.
#
# Not `if ! git push; then PUSH_RC=$?; fi` either: `!` inverts the status, so
# the captured value is the negation's 0. That form looks repaired and is not.
PUSH_RC=0
git push -u origin "$BRANCH" || PUSH_RC=$?

# `|| REMOTE_SHA=""` is load-bearing. Under `pipefail` a failed ls-remote fails
# this assignment and `set -e` kills the script one line before the check,
# reintroducing the silent stop for every remote-unreachable case: network
# down, repo renamed, credential revoked.
LOCAL_SHA=$(git rev-parse HEAD)
REMOTE_SHA=$(git ls-remote origin "$BRANCH" 2>/dev/null | cut -f1) || REMOTE_SHA=""

# Verify the OBJECT, not the exit code. `git push` can report success on a path
# that did not deliver, and a backup that announces success without checking is
# the highest-stakes version of that failure -- it is the thing protecting the
# being's memory.
if [ "$LOCAL_SHA" != "$REMOTE_SHA" ]; then
  echo "BACKUP FAILED: local $LOCAL_SHA != remote ${{REMOTE_SHA:-<unreachable>}} (push rc=$PUSH_RC)" >&2
  exit 1
fi

echo "Backup verified: $BRANCH at $LOCAL_SHA"
"""


def scaffold_github_backup(config: HatchConfig) -> dict[str, Any] | None:
    if not config.channels.github_backup.enabled:
        return None

    hook_dir = config.resolved_vault_root() / "hooks"
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hook_dir / "backup-to-github.sh"
    hook_path.write_text(
        _HOOK_TEMPLATE.format(
            being_name=config.being_name,
            being_name_lower=config.being_name_lower,
            vault_root=str(config.resolved_vault_root()).replace("\\", "/"),
            repo_url=config.channels.github_backup.repo_url,
        ),
        encoding="utf-8",
    )
    if os.name != "nt":
        hook_path.chmod(0o755)

    job_name = f"{config.being_name_lower}-github_backup"
    return {
        job_name: {
            "trigger": "cron",
            "timezone": "America/New_York",
            "schedule": {"hour": 4, "minute": 30},
            "target": config.endpoint_name,
            "envelope_kind": "Event",
            "payload": {
                "type": "GitHubBackup",
                "data": {"hook_path": str(hook_path)},
            },
        }
    }
