"""GitHub backup scaffolding (CW-4 — opt-in)."""

from __future__ import annotations

import os
from typing import Any

from agent_core_hatchery.config import HatchConfig

_HOOK_TEMPLATE = """#!/usr/bin/env bash
# Generated by agent-core-hatchery for {being_name}.
# Backup the vault's Memory/ to GitHub. Invoked by the
# {being_name_lower}-github_backup scheduler job.
set -euo pipefail

VAULT_ROOT="{vault_root}"
REPO_URL="{repo_url}"

cd "$VAULT_ROOT"
if [ ! -d Memory/.git ]; then
  cd Memory
  git init
  git remote add origin "$REPO_URL"
  cd ..
fi
cd Memory
git add -A
git commit -m "backup $(date -Iseconds)" || true  # ok if nothing to commit
git push -u origin HEAD || true                   # warn-only on first push
"""


def scaffold_github_backup(config: HatchConfig) -> dict[str, Any] | None:
    if not config.channels.github_backup.enabled:
        return None

    hook_dir = config.resolved_vault_root() / "hooks"
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hook_dir / "backup-to-github.sh"
    hook_path.write_text(
        _HOOK_TEMPLATE.format(
            being_name=config.being_name,
            being_name_lower=config.being_name_lower,
            vault_root=str(config.resolved_vault_root()).replace("\\", "/"),
            repo_url=config.channels.github_backup.repo_url,
        ),
        encoding="utf-8",
    )
    if os.name != "nt":
        hook_path.chmod(0o755)

    job_name = f"{config.being_name_lower}-github_backup"
    return {
        job_name: {
            "trigger": "cron",
            "timezone": "America/New_York",
            "schedule": {"hour": 4, "minute": 30},
            "target": config.endpoint_name,
            "envelope_kind": "Event",
            "payload": {
                "type": "GitHubBackup",
                "data": {"hook_path": str(hook_path)},
            },
        }
    }
