"""Tests for ``MarkdownFileDestination``.

The destination is filesystem-only — no bus traffic — so tests use a
no-op recording handle just to satisfy the ``deliver()`` signature.
File writes land under ``tmp_path``; no I/O escapes the test sandbox.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pytest
from agent_core_briefs.destinations.markdown_file import MarkdownFileDestination
from agent_core_briefs.protocol import (
    Destination,
    PlaybookRef,
    validate_destination_signature,
)


class _NoopHandle:
    """Bus handle that is never used — markdown_file ignores its handle."""

    async def publish(self, envelope, to=None) -> None:  # pragma: no cover
        raise AssertionError("markdown_file must not call publish()")

    async def ack(self, envelope_id: str) -> None: ...
    async def nack(self, envelope_id: str, requeue: bool = True) -> None: ...

    def endpoints(self):
        return []


def _playbook(tmp_path: Path | None = None, brief_type: str = "morning_brief") -> PlaybookRef:
    return PlaybookRef(
        brief_type=brief_type,
        path=(tmp_path or Path(".")) / f"{brief_type}.md",
        sections_required=["greeting"],
        sections_optional=[],
    )


def _section(
    *,
    title: str = "🌅 Morning",
    fields: list[dict] | None = None,
) -> dict:
    return {
        "title": title,
        "fields": fields if fields is not None else [{"name": "Today", "value": "Sunny day"}],
    }


def test_destination_satisfies_runtime_protocol() -> None:
    assert isinstance(MarkdownFileDestination(), Destination)


def test_validate_destination_signature_passes() -> None:
    """The class's ``deliver`` must satisfy T11's signature validator."""
    validate_destination_signature(MarkdownFileDestination())  # must not raise


@pytest.mark.asyncio
async def test_writes_file_at_configured_path(tmp_path: Path) -> None:
    """Happy path: file is written, contains H1, H2 per section, field values."""
    dest = MarkdownFileDestination()
    out = tmp_path / "brief.md"
    sections = [
        _section(title="🌅 Morning", fields=[{"name": "Today", "value": "Sunny"}]),
        _section(title="📅 Calendar", fields=[{"name": "Schedule", "value": "09:00 standup"}]),
    ]
    when = datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC)

    result = await dest.deliver(
        sections=sections,
        playbook=_playbook(tmp_path),
        scope="today",
        when=when,
        config={"path": str(out)},
        bus_handle=_NoopHandle(),
    )

    assert result.success is True
    assert out.exists()
    content = out.read_text(encoding="utf-8")
    # H1 with brief_type and ISO timestamp
    assert "# morning_brief — 2026-05-04T07:00:00+00:00" in content
    # One H2 per section
    assert "## 🌅 Morning" in content
    assert "## 📅 Calendar" in content
    # Bold field names + values
    assert "**Today**" in content
    assert "Sunny" in content
    assert "**Schedule**" in content
    assert "09:00 standup" in content
    # Footer
    assert "_Generated by agent_core_briefs" in content


@pytest.mark.asyncio
async def test_path_supports_when_date_template(tmp_path: Path) -> None:
    """``{{when.date}}`` substitutes to the ISO date."""
    dest = MarkdownFileDestination()
    when = datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC)

    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope=None,
        when=when,
        config={"path": str(tmp_path / "{{when.date}}-morning.md")},
        bus_handle=_NoopHandle(),
    )

    assert result.success is True
    expected = tmp_path / "2026-05-04-morning.md"
    assert expected.exists()
    assert result.ref == str(expected.resolve())


@pytest.mark.asyncio
async def test_path_supports_brief_type_template(tmp_path: Path) -> None:
    """``{{brief_type}}`` substitutes to the playbook's brief_type."""
    dest = MarkdownFileDestination()
    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path, brief_type="morning_brief"),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(tmp_path / "{{brief_type}}.md")},
        bus_handle=_NoopHandle(),
    )

    assert result.success is True
    assert (tmp_path / "morning_brief.md").exists()


@pytest.mark.asyncio
async def test_path_supports_combined_templates(tmp_path: Path) -> None:
    """Year/month/day + brief_type compose into a nested-dated path."""
    dest = MarkdownFileDestination()
    when = datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC)

    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path, brief_type="morning_brief"),
        scope=None,
        when=when,
        config={
            "path": str(tmp_path / "{{when.year}}/{{when.month}}/{{when.day}}-{{brief_type}}.md"),
        },
        bus_handle=_NoopHandle(),
    )

    assert result.success is True
    expected = tmp_path / "2026" / "05" / "04-morning_brief.md"
    assert expected.exists()


@pytest.mark.asyncio
async def test_creates_parent_directories(tmp_path: Path) -> None:
    """Missing parent dirs are created (parents=True)."""
    dest = MarkdownFileDestination()
    nested = tmp_path / "nested" / "dir" / "file.md"
    assert not nested.parent.exists()

    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(nested)},
        bus_handle=_NoopHandle(),
    )

    assert result.success is True
    assert nested.exists()


@pytest.mark.asyncio
async def test_scope_line_omitted_when_none(tmp_path: Path) -> None:
    dest = MarkdownFileDestination()
    out = tmp_path / "no-scope.md"

    await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(out)},
        bus_handle=_NoopHandle(),
    )

    content = out.read_text(encoding="utf-8")
    assert "_Scope:" not in content


@pytest.mark.asyncio
async def test_scope_line_present_when_set(tmp_path: Path) -> None:
    dest = MarkdownFileDestination()
    out = tmp_path / "with-scope.md"

    await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope="today",
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(out)},
        bus_handle=_NoopHandle(),
    )

    content = out.read_text(encoding="utf-8")
    assert "_Scope: today_" in content


@pytest.mark.asyncio
async def test_delivery_result_carries_absolute_path_as_ref(tmp_path: Path) -> None:
    dest = MarkdownFileDestination()
    out = tmp_path / "ref.md"

    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(out)},
        bus_handle=_NoopHandle(),
    )

    assert result.success is True
    assert result.error is None
    assert result.ref == str(out.resolve())
    # ref is absolute
    assert Path(result.ref).is_absolute()


@pytest.mark.asyncio
async def test_unknown_template_key_returns_failure(tmp_path: Path) -> None:
    """Unknown ``{{...}}`` keys land in DeliveryResult, not as raised exceptions."""
    dest = MarkdownFileDestination()
    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(tmp_path / "{{when.unknown}}.md")},
        bus_handle=_NoopHandle(),
    )

    assert result.success is False
    assert result.ref is None
    assert result.error is not None
    assert "unknown" in result.error
    # Nothing should have been written
    assert list(tmp_path.iterdir()) == []


@pytest.mark.asyncio
async def test_missing_path_config_returns_failure(tmp_path: Path) -> None:
    dest = MarkdownFileDestination()
    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={},
        bus_handle=_NoopHandle(),
    )

    assert result.success is False
    assert result.ref is None
    assert result.error is not None
    assert "path" in result.error


@pytest.mark.asyncio
async def test_no_sections_writes_empty_brief(tmp_path: Path) -> None:
    """Empty sections still produces a file (H1 + footer, no H2). Audit trails
    benefit from always having an artifact for a triggered brief."""
    dest = MarkdownFileDestination()
    out = tmp_path / "empty.md"

    result = await dest.deliver(
        sections=[],
        playbook=_playbook(tmp_path),
        scope="today",
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(out)},
        bus_handle=_NoopHandle(),
    )

    assert result.success is True
    assert out.exists()
    content = out.read_text(encoding="utf-8")
    assert "# morning_brief — 2026-05-04T07:00:00+00:00" in content
    assert "_Scope: today_" in content
    assert "## " not in content  # no section headers
    assert "_Generated by agent_core_briefs" in content


@pytest.mark.asyncio
async def test_multiline_field_values_preserved(tmp_path: Path) -> None:
    """Multi-line field values pass through verbatim via ``str(value)``."""
    dest = MarkdownFileDestination()
    out = tmp_path / "multiline.md"
    multi = "line one\nline two\nline three"

    await dest.deliver(
        sections=[_section(fields=[{"name": "Notes", "value": multi}])],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(out)},
        bus_handle=_NoopHandle(),
    )

    content = out.read_text(encoding="utf-8")
    assert multi in content


@pytest.mark.asyncio
async def test_uses_async_to_thread_for_io(tmp_path: Path, monkeypatch) -> None:
    """The disk write goes through ``asyncio.to_thread`` to honor T4's
    cancellation contract — same lesson as T5's filesystem_read fix."""
    import agent_core_briefs.destinations.markdown_file as module

    calls: list[tuple] = []
    real_to_thread = module.asyncio.to_thread

    async def _spy(func, *args, **kwargs):
        calls.append((func, args, kwargs))
        return await real_to_thread(func, *args, **kwargs)

    monkeypatch.setattr(module.asyncio, "to_thread", _spy)

    dest = MarkdownFileDestination()
    out = tmp_path / "spied.md"
    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(out)},
        bus_handle=_NoopHandle(),
    )

    assert result.success is True
    assert len(calls) == 1
    # The function passed to to_thread is the static _write_file
    assert calls[0][0] is MarkdownFileDestination._write_file


@pytest.mark.asyncio
async def test_os_error_during_write_returns_failure(tmp_path: Path) -> None:
    """Parent path is a regular file, not a directory — ``mkdir(parents=True)``
    raises ``NotADirectoryError`` (an ``OSError`` subclass) and we surface it
    as ``DeliveryResult(success=False)`` rather than letting it propagate."""
    blocker = tmp_path / "blocker"
    blocker.write_text("I am a file, not a directory", encoding="utf-8")

    dest = MarkdownFileDestination()
    result = await dest.deliver(
        sections=[_section()],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(blocker / "child.md")},  # parent is a file
        bus_handle=_NoopHandle(),
    )

    assert result.success is False
    assert result.ref is None
    assert result.error is not None
    assert "write failed" in result.error


@pytest.mark.asyncio
async def test_unicode_error_during_write_returns_failure(tmp_path: Path) -> None:
    """Encoding mismatch (``ascii`` encoding + emoji content) raises
    ``UnicodeEncodeError``; verify it lands in ``DeliveryResult`` per the
    docstring's failure contract. ``UnicodeError`` is NOT an ``OSError``
    subclass, so this exercises the broadened ``except`` clause."""
    dest = MarkdownFileDestination()
    result = await dest.deliver(
        sections=[
            _section(
                title="🌅 Morning",  # non-ASCII
                fields=[{"name": "Today", "value": "✓ done"}],
            )
        ],
        playbook=_playbook(tmp_path),
        scope=None,
        when=datetime(2026, 5, 4, 7, 0, 0, tzinfo=UTC),
        config={"path": str(tmp_path / "out.md"), "encoding": "ascii"},
        bus_handle=_NoopHandle(),
    )

    assert result.success is False
    assert result.ref is None
    assert result.error is not None
    assert "write failed" in result.error
